package services

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/jomei/notionapi"
	"github.com/rizkajuliant20/bug-bot/pkg/logger"
	"github.com/slack-go/slack"
)

type NotionService struct {
	client     *notionapi.Client
	databaseID notionapi.DatabaseID
	apiToken   string
	logger     *logger.Logger
}

type MediaFile struct {
	URL      string
	Name     string
	MimeType string
	IsImage  bool
	IsVideo  bool
}

type BugTicketData struct {
	Title          string
	Description    string
	Diagnosis      *BugDiagnosis
	Reporter       string
	SlackThreadURL string
	ThreadMessages []slack.Message
	ThreadSummary  string
	MediaFiles     []MediaFile // Screenshots, images, videos from Slack
	// Jago-specific fields
	CreatedBy    string
	Assignee     string
	Environment  string
	Reproducible bool
	Impact       string
	Urgency      string
	DueDate      time.Time
}

func NewNotionService(apiKey, databaseID string, log *logger.Logger) *NotionService {
	client := notionapi.NewClient(notionapi.Token(apiKey))
	return &NotionService{
		client:     client,
		databaseID: notionapi.DatabaseID(databaseID),
		apiToken:   apiKey,
		logger:     log,
	}
}

// getAssigneeByApp returns assignee name based on app tags
func getAssigneeByApp(tags []string) string {
	for _, tag := range tags {
		switch tag {
		case "Jago App":
			return "Janaka Jati Lasmana"
		case "Jagoan App":
			return "Santo Malau"
		}
	}
	return "" // No auto-assignment for other apps
}

func (s *NotionService) CreateBugTicket(data *BugTicketData, slackService *SlackService) (*notionapi.Page, error) {
	s.logger.Flow("NOTION_SERVICE", "Creating bug ticket", map[string]interface{}{
		"title": data.Title,
	})

	// Build properties
	properties := notionapi.Properties{
		"Task name": notionapi.TitleProperty{
			Type: notionapi.PropertyTypeTitle,
			Title: []notionapi.RichText{
				{
					Type: notionapi.ObjectTypeText,
					Text: &notionapi.Text{Content: data.Title},
				},
			},
		},
		"Status": notionapi.StatusProperty{
			Type:   notionapi.PropertyTypeStatus,
			Status: notionapi.Status{Name: "Not started"},
		},
	}

	// Add diagnosis properties
	if data.Diagnosis != nil {
		properties["Priority"] = notionapi.SelectProperty{
			Type:   notionapi.PropertyTypeSelect,
			Select: notionapi.Option{Name: data.Diagnosis.Priority},
		}
		properties["Team"] = notionapi.SelectProperty{
			Type:   notionapi.PropertyTypeSelect,
			Select: notionapi.Option{Name: data.Diagnosis.Team},
		}

		// Platform multi-select
		if len(data.Diagnosis.Platform) > 0 {
			var platformOptions []notionapi.Option
			for _, p := range data.Diagnosis.Platform {
				platformOptions = append(platformOptions, notionapi.Option{Name: p})
			}
			properties["Platform"] = notionapi.MultiSelectProperty{
				Type:        notionapi.PropertyTypeMultiSelect,
				MultiSelect: platformOptions,
			}
		}

		// Tags multi-select
		if len(data.Diagnosis.Tags) > 0 {
			var tagOptions []notionapi.Option
			for _, t := range data.Diagnosis.Tags {
				tagOptions = append(tagOptions, notionapi.Option{Name: t})
			}
			properties["Tags"] = notionapi.MultiSelectProperty{
				Type:        notionapi.PropertyTypeMultiSelect,
				MultiSelect: tagOptions,
			}
		}
	}

	// Add Slack Thread URL
	if data.SlackThreadURL != "" {
		properties["Slack Thread"] = notionapi.URLProperty{
			Type: notionapi.PropertyTypeURL,
			URL:  data.SlackThreadURL,
		}
	}

	// Auto-assign based on app tags
	if data.Diagnosis != nil && len(data.Diagnosis.Tags) > 0 {
		assignee := getAssigneeByApp(data.Diagnosis.Tags)
		if assignee != "" {
			// Note: Assignee in Notion is Person type which requires user IDs
			// For now, we'll add as text in Summary or create a separate text field
			// Alternatively, can be set manually in Notion based on tags
			s.logger.Info("Auto-assignee determined", map[string]interface{}{
				"assignee": assignee,
				"tags":     data.Diagnosis.Tags,
			})
			// Store in data for later use if needed
			data.Assignee = assignee
		}
	}

	// Note: Due Date, Sprint, Summary are managed manually in Notion
	// Created By is auto-generated by Notion based on who creates the ticket
	// Assignee (Person field) needs to be set manually or via user IDs

	// Build page content
	children := s.buildPageContent(data)

	// Create page
	page, err := s.client.Page.Create(context.Background(), &notionapi.PageCreateRequest{
		Parent: notionapi.Parent{
			Type:       notionapi.ParentTypeDatabaseID,
			DatabaseID: s.databaseID,
		},
		Properties: properties,
		Children:   children,
	})

	if err != nil {
		s.logger.Error("Failed to create Notion page", err, nil)
		return nil, fmt.Errorf("failed to create notion page: %w", err)
	}

	s.logger.Success("Bug ticket created successfully", map[string]interface{}{
		"pageId": page.ID,
	})

	// Note: Media files are shown as text references in the page content
	// Direct upload is blocked by Cloudflare protection on Notion's upload endpoint
	if len(data.MediaFiles) > 0 {
		s.logger.Info("Media files listed in ticket (Cloudflare blocks direct upload)", map[string]interface{}{
			"count": len(data.MediaFiles),
		})
	}

	return page, nil
}

// Helper function to convert text to bullet points
func textToBulletPoints(text string) []notionapi.Block {
	var blocks []notionapi.Block
	lines := strings.Split(text, "\n")

	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}

		// Remove existing bullet/dash if present
		line = strings.TrimPrefix(line, "- ")
		line = strings.TrimPrefix(line, "• ")

		blocks = append(blocks, notionapi.BulletedListItemBlock{
			BasicBlock: notionapi.BasicBlock{
				Object: notionapi.ObjectTypeBlock,
				Type:   notionapi.BlockTypeBulletedListItem,
			},
			BulletedListItem: notionapi.ListItem{
				RichText: []notionapi.RichText{
					{
						Type: notionapi.ObjectTypeText,
						Text: &notionapi.Text{Content: line},
					},
				},
			},
		})
	}

	return blocks
}

// Helper function to parse numbered lists and create proper Notion blocks
func parseStepsToBlocks(text string) []notionapi.Block {
	var blocks []notionapi.Block
	lines := strings.Split(text, "\n")

	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}

		// Check if line starts with number (e.g., "1. ", "2. ")
		if len(line) > 2 && line[0] >= '1' && line[0] <= '9' && line[1] == '.' {
			// Extract text after "1. "
			stepText := strings.TrimSpace(line[2:])
			blocks = append(blocks, notionapi.NumberedListItemBlock{
				BasicBlock: notionapi.BasicBlock{
					Object: notionapi.ObjectTypeBlock,
					Type:   notionapi.BlockTypeNumberedListItem,
				},
				NumberedListItem: notionapi.ListItem{
					RichText: []notionapi.RichText{
						{
							Type: notionapi.ObjectTypeText,
							Text: &notionapi.Text{Content: stepText},
						},
					},
				},
			})
		} else {
			// Regular paragraph
			blocks = append(blocks, notionapi.ParagraphBlock{
				BasicBlock: notionapi.BasicBlock{
					Object: notionapi.ObjectTypeBlock,
					Type:   notionapi.BlockTypeParagraph,
				},
				Paragraph: notionapi.Paragraph{
					RichText: []notionapi.RichText{
						{
							Type: notionapi.ObjectTypeText,
							Text: &notionapi.Text{Content: line},
						},
					},
				},
			})
		}
	}

	return blocks
}

func (s *NotionService) buildPageContent(data *BugTicketData) []notionapi.Block {
	var blocks []notionapi.Block

	// Add suggested assignee callout if available
	if data.Assignee != "" {
		blocks = append(blocks, notionapi.CalloutBlock{
			BasicBlock: notionapi.BasicBlock{
				Object: notionapi.ObjectTypeBlock,
				Type:   notionapi.BlockTypeCallout,
			},
			Callout: notionapi.Callout{
				RichText: []notionapi.RichText{
					{
						Type:        notionapi.ObjectTypeText,
						Text:        &notionapi.Text{Content: fmt.Sprintf("👤 Suggested Assignee: %s", data.Assignee)},
						Annotations: &notionapi.Annotations{Bold: true},
					},
				},
				Color: "blue_background",
			},
		})
	}

	// Bug Description
	blocks = append(blocks, notionapi.Heading2Block{
		BasicBlock: notionapi.BasicBlock{
			Object: notionapi.ObjectTypeBlock,
			Type:   notionapi.BlockTypeHeading2,
		},
		Heading2: notionapi.Heading{
			RichText: []notionapi.RichText{
				{Type: notionapi.ObjectTypeText, Text: &notionapi.Text{Content: "🐛 Bug Description"}},
			},
		},
	})

	blocks = append(blocks, notionapi.ParagraphBlock{
		BasicBlock: notionapi.BasicBlock{
			Object: notionapi.ObjectTypeBlock,
			Type:   notionapi.BlockTypeParagraph,
		},
		Paragraph: notionapi.Paragraph{
			RichText: []notionapi.RichText{
				{Type: notionapi.ObjectTypeText, Text: &notionapi.Text{Content: data.Description}},
			},
		},
	})

	if data.Diagnosis != nil {
		// Precondition
		if data.Diagnosis.Precondition != "" {
			blocks = append(blocks, notionapi.Heading3Block{
				BasicBlock: notionapi.BasicBlock{Object: notionapi.ObjectTypeBlock, Type: notionapi.BlockTypeHeading3},
				Heading3:   notionapi.Heading{RichText: []notionapi.RichText{{Type: notionapi.ObjectTypeText, Text: &notionapi.Text{Content: "Precondition"}}}},
			})
			bulletBlocks := textToBulletPoints(data.Diagnosis.Precondition)
			blocks = append(blocks, bulletBlocks...)
		}

		// Steps to Reproduce
		if data.Diagnosis.StepsToReproduce != "" {
			blocks = append(blocks, notionapi.Heading3Block{
				BasicBlock: notionapi.BasicBlock{Object: notionapi.ObjectTypeBlock, Type: notionapi.BlockTypeHeading3},
				Heading3:   notionapi.Heading{RichText: []notionapi.RichText{{Type: notionapi.ObjectTypeText, Text: &notionapi.Text{Content: "Steps to Reproduce"}}}},
			})
			// Parse and add steps as numbered list
			stepBlocks := parseStepsToBlocks(data.Diagnosis.StepsToReproduce)
			blocks = append(blocks, stepBlocks...)
		}

		// Actual Result
		if data.Diagnosis.ActualResult != "" {
			blocks = append(blocks, notionapi.Heading3Block{
				BasicBlock: notionapi.BasicBlock{Object: notionapi.ObjectTypeBlock, Type: notionapi.BlockTypeHeading3},
				Heading3:   notionapi.Heading{RichText: []notionapi.RichText{{Type: notionapi.ObjectTypeText, Text: &notionapi.Text{Content: "Actual Result"}}}},
			})
			bulletBlocks := textToBulletPoints(data.Diagnosis.ActualResult)
			blocks = append(blocks, bulletBlocks...)
		}

		// Expected Result
		if data.Diagnosis.ExpectedResult != "" {
			blocks = append(blocks, notionapi.Heading3Block{
				BasicBlock: notionapi.BasicBlock{Object: notionapi.ObjectTypeBlock, Type: notionapi.BlockTypeHeading3},
				Heading3:   notionapi.Heading{RichText: []notionapi.RichText{{Type: notionapi.ObjectTypeText, Text: &notionapi.Text{Content: "Expected Result"}}}},
			})
			bulletBlocks := textToBulletPoints(data.Diagnosis.ExpectedResult)
			blocks = append(blocks, bulletBlocks...)
		}

		// QA Diagnosis
		blocks = append(blocks, notionapi.Heading2Block{
			BasicBlock: notionapi.BasicBlock{Object: notionapi.ObjectTypeBlock, Type: notionapi.BlockTypeHeading2},
			Heading2:   notionapi.Heading{RichText: []notionapi.RichText{{Type: notionapi.ObjectTypeText, Text: &notionapi.Text{Content: "🔍 QA Diagnosis"}}}},
		})

		// Root Cause as bullet points
		blocks = append(blocks, notionapi.Heading3Block{
			BasicBlock: notionapi.BasicBlock{Object: notionapi.ObjectTypeBlock, Type: notionapi.BlockTypeHeading3},
			Heading3:   notionapi.Heading{RichText: []notionapi.RichText{{Type: notionapi.ObjectTypeText, Text: &notionapi.Text{Content: "Root Cause"}}}},
		})
		bulletBlocks := textToBulletPoints(data.Diagnosis.RootCause)
		blocks = append(blocks, bulletBlocks...)

		// Suggested Fix as bullet points
		blocks = append(blocks, notionapi.Heading3Block{
			BasicBlock: notionapi.BasicBlock{Object: notionapi.ObjectTypeBlock, Type: notionapi.BlockTypeHeading3},
			Heading3:   notionapi.Heading{RichText: []notionapi.RichText{{Type: notionapi.ObjectTypeText, Text: &notionapi.Text{Content: "Suggested Fix"}}}},
		})
		bulletBlocks = textToBulletPoints(data.Diagnosis.SuggestedFix)
		blocks = append(blocks, bulletBlocks...)
	}

	// Media Files (as direct clickable links)
	if len(data.MediaFiles) > 0 {
		blocks = append(blocks, notionapi.Heading2Block{
			BasicBlock: notionapi.BasicBlock{Object: notionapi.ObjectTypeBlock, Type: notionapi.BlockTypeHeading2},
			Heading2:   notionapi.Heading{RichText: []notionapi.RichText{{Type: notionapi.ObjectTypeText, Text: &notionapi.Text{Content: "📷 Screenshots & Media"}}}},
		})

		// Add clickable link for each media file
		for i, media := range data.MediaFiles {
			mediaIcon := "📎"
			mediaLabel := "File"
			if media.IsImage {
				mediaIcon = "🖼️"
				mediaLabel = "Image"
			} else if media.IsVideo {
				mediaIcon = "🎥"
				mediaLabel = "Video"
			}

			blocks = append(blocks, notionapi.ParagraphBlock{
				BasicBlock: notionapi.BasicBlock{Object: notionapi.ObjectTypeBlock, Type: notionapi.BlockTypeParagraph},
				Paragraph: notionapi.Paragraph{
					RichText: []notionapi.RichText{
						{
							Type: notionapi.ObjectTypeText,
							Text: &notionapi.Text{Content: fmt.Sprintf("%s %d. ", mediaIcon, i+1)},
						},
						{
							Type: notionapi.ObjectTypeText,
							Text: &notionapi.Text{
								Content: mediaLabel,
								Link:    &notionapi.Link{Url: media.URL},
							},
						},
					},
				},
			})
		}
	}

	// Thread Summary
	if data.ThreadSummary != "" {
		blocks = append(blocks, notionapi.Heading2Block{
			BasicBlock: notionapi.BasicBlock{Object: notionapi.ObjectTypeBlock, Type: notionapi.BlockTypeHeading2},
			Heading2:   notionapi.Heading{RichText: []notionapi.RichText{{Type: notionapi.ObjectTypeText, Text: &notionapi.Text{Content: "💬 Thread Summary"}}}},
		})
		bulletBlocks := textToBulletPoints(data.ThreadSummary)
		blocks = append(blocks, bulletBlocks...)
	}

	return blocks
}

func (s *NotionService) GetNotionPageURL(pageID string) string {
	cleanID := strings.ReplaceAll(pageID, "-", "")
	return fmt.Sprintf("https://notion.so/%s", cleanID)
}

// Notion Polling
type TrackedBugs struct {
	BugIDs []string `json:"bugIds"`
}

const trackingFile = ".notion-tracking.json"

func (s *NotionService) PollForNewBugs(bugTrackingChannel string, slackService *SlackService) error {
	s.logger.Flow("NOTION_POLLING", "Starting poll cycle", nil)

	trackedBugs := s.loadTrackedBugs()

	// Query Notion for recent bugs (last 10 minutes)
	tenMinutesAgo := time.Now().Add(-10 * time.Minute).Format(time.RFC3339)
	s.logger.Info("Querying Notion database", map[string]interface{}{"since": tenMinutesAgo})

	query, err := s.client.Database.Query(context.Background(), s.databaseID, &notionapi.DatabaseQueryRequest{
		Sorts: []notionapi.SortObject{
			{
				Timestamp: "created_time",
				Direction: notionapi.SortOrderDESC,
			},
		},
	})

	if err != nil {
		s.logger.Error("Notion query failed", err, nil)
		return err
	}

	s.logger.Info("Notion query completed", map[string]interface{}{"totalResults": len(query.Results)})

	newBugs := 0
	for _, page := range query.Results {
		pageID := page.ID.String()

		// Skip if already tracked
		if contains(trackedBugs.BugIDs, pageID) {
			continue
		}

		s.logger.Flow("NOTION_POLLING", "Processing new page", map[string]interface{}{"pageId": pageID})

		// Extract properties
		title := extractTitle(page.Properties)
		tags := extractMultiSelect(page.Properties, "Tags")
		slackThread := extractURL(page.Properties, "Slack Thread")

		// Skip if no bug tag
		if !containsIgnoreCase(tags, "bug") {
			s.logger.Info("Skipping page without bug tag", map[string]interface{}{"pageId": pageID, "tags": tags})
			trackedBugs.BugIDs = append(trackedBugs.BugIDs, pageID)
			continue
		}

		// Skip if automation-created (has Slack Thread URL)
		if slackThread != "" {
			s.logger.Info("Skipping automation-created bug", map[string]interface{}{"pageId": pageID, "slackThread": slackThread})
			trackedBugs.BugIDs = append(trackedBugs.BugIDs, pageID)
			continue
		}

		s.logger.Success("Found manually created bug", map[string]interface{}{"pageId": pageID, "title": title})

		// Send notification
		if bugTrackingChannel != "" {
			s.sendBugNotification(slackService, bugTrackingChannel, page)
		}

		trackedBugs.BugIDs = append(trackedBugs.BugIDs, pageID)
		newBugs++
	}

	if newBugs > 0 {
		s.logger.Success("Poll cycle completed", map[string]interface{}{"newBugsFound": newBugs})
		s.saveTrackedBugs(trackedBugs)
	} else {
		s.logger.Info("Poll cycle completed - no new bugs found", nil)
	}

	return nil
}

func (s *NotionService) sendBugNotification(slackService *SlackService, channel string, page notionapi.Page) {
	title := extractTitle(page.Properties)
	severity := extractSelect(page.Properties, "Severity")
	priority := extractSelect(page.Properties, "Priority")
	category := extractSelect(page.Properties, "Category")
	reporter := extractRichText(page.Properties, "Reporter")
	platform := extractMultiSelect(page.Properties, "Platform")

	notionURL := s.GetNotionPageURL(page.ID.String())

	s.logger.Flow("NOTION_POLLING", "Sending bug notification", map[string]interface{}{"bugId": page.ID, "title": title})

	blocks := []slack.Block{
		slack.NewHeaderBlock(&slack.TextBlockObject{Type: slack.PlainTextType, Text: "🐛 New Bug Ticket"}),
		slack.NewSectionBlock(
			nil,
			[]*slack.TextBlockObject{
				{Type: slack.MarkdownType, Text: fmt.Sprintf("*Title:*\n%s", title)},
				{Type: slack.MarkdownType, Text: fmt.Sprintf("*Reporter:*\n%s", reporter)},
				{Type: slack.MarkdownType, Text: fmt.Sprintf("*Severity:*\n%s", severity)},
				{Type: slack.MarkdownType, Text: fmt.Sprintf("*Priority:*\n%s", priority)},
			},
			nil,
		),
		slack.NewSectionBlock(
			&slack.TextBlockObject{Type: slack.MarkdownType, Text: fmt.Sprintf("*Category:* %s\n*Platform:* %s", category, strings.Join(platform, ", "))},
			nil,
			nil,
		),
		slack.NewActionBlock(
			"",
			slack.NewButtonBlockElement("", "", &slack.TextBlockObject{Type: slack.PlainTextType, Text: "📝 View in Notion"}).WithURL(notionURL).WithStyle(slack.StylePrimary),
		),
	}

	if err := slackService.PostMessage(channel, fmt.Sprintf("🐛 New bug ticket created manually: %s", title), blocks); err != nil {
		s.logger.Error("Failed to send bug notification", err, map[string]interface{}{"bugId": page.ID, "title": title})
	} else {
		s.logger.Success("Notification sent for manually created bug", map[string]interface{}{"bugId": page.ID, "title": title})
	}
}

func (s *NotionService) loadTrackedBugs() *TrackedBugs {
	data, err := os.ReadFile(trackingFile)
	if err != nil {
		s.logger.Info("Tracked bugs file not found, starting fresh", nil)
		return &TrackedBugs{BugIDs: []string{}}
	}

	var tracked TrackedBugs
	if err := json.Unmarshal(data, &tracked); err != nil {
		s.logger.Error("Failed to parse tracked bugs", err, nil)
		return &TrackedBugs{BugIDs: []string{}}
	}

	s.logger.Info("Tracked bugs loaded", map[string]interface{}{"count": len(tracked.BugIDs)})
	return &tracked
}

func (s *NotionService) saveTrackedBugs(tracked *TrackedBugs) {
	data, err := json.MarshalIndent(tracked, "", "  ")
	if err != nil {
		s.logger.Error("Failed to marshal tracked bugs", err, nil)
		return
	}

	if err := os.WriteFile(trackingFile, data, 0644); err != nil {
		s.logger.Error("Failed to save tracked bugs", err, nil)
		return
	}

	s.logger.Info("Tracked bugs saved", map[string]interface{}{"count": len(tracked.BugIDs)})
}

// Helper functions
func extractTitle(props notionapi.Properties) string {
	if title, ok := props["Title"].(*notionapi.TitleProperty); ok && len(title.Title) > 0 {
		return title.Title[0].PlainText
	}
	return "Untitled"
}

func extractSelect(props notionapi.Properties, name string) string {
	if sel, ok := props[name].(*notionapi.SelectProperty); ok && sel.Select.Name != "" {
		return sel.Select.Name
	}
	return "Unknown"
}

func extractMultiSelect(props notionapi.Properties, name string) []string {
	if ms, ok := props[name].(*notionapi.MultiSelectProperty); ok {
		var values []string
		for _, opt := range ms.MultiSelect {
			values = append(values, opt.Name)
		}
		return values
	}
	return []string{}
}

func extractRichText(props notionapi.Properties, name string) string {
	if rt, ok := props[name].(*notionapi.RichTextProperty); ok && len(rt.RichText) > 0 {
		return rt.RichText[0].PlainText
	}
	return "Unknown"
}

func extractURL(props notionapi.Properties, name string) string {
	if url, ok := props[name].(*notionapi.URLProperty); ok {
		return url.URL
	}
	return ""
}

func contains(slice []string, item string) bool {
	for _, s := range slice {
		if s == item {
			return true
		}
	}
	return false
}

func containsIgnoreCase(slice []string, item string) bool {
	lowerItem := strings.ToLower(item)
	for _, s := range slice {
		if strings.ToLower(s) == lowerItem {
			return true
		}
	}
	return false
}

func (s *NotionService) StartPolling(interval time.Duration, bugTrackingChannel string, slackService *SlackService) {
	s.logger.Success("Notion polling service started", map[string]interface{}{"intervalMinutes": interval.Minutes()})

	// Initial poll
	s.logger.Info("Running initial poll", nil)
	s.PollForNewBugs(bugTrackingChannel, slackService)

	// Set up ticker
	ticker := time.NewTicker(interval)
	go func() {
		for range ticker.C {
			s.PollForNewBugs(bugTrackingChannel, slackService)
		}
	}()
}
